#!/bin/sh
# location path: /usr/local/sbin
# in /etc/rc.local must execute keyctl link $(keyctl show @us | grep TOTPKEY | awk '{print $1}') @s

#set -x

TTY=/dev/tty0
#TTY=/dev/stderr
NUL=/dev/null
OTPkey="TOTPKEY"
HTTPPORT=8080
QRAUTHFN="qrauth.txt"
PTPPATH="/store_00010001/Pictures"
cd /tmp

# workaround because of changing passsword for LUKS disk not working properly inner this script
LUKSPASSCHANGED_KEYRING_ID=`keyctl search @u user "LUKSPASSCHANGED" 2>$NUL`
if [ ! -z "$LUKSPASSCHANGED_KEYRING_ID" ]; then
  keyctl pipe $LUKSPASSCHANGED_KEYRING_ID
  keyctl unlink $LUKSPASSCHANGED_KEYRING_ID >$TTY
  exit 0
fi

KEYRING_ID=`keyctl search @u user "$OTPkey" 2>$NUL`
#echo "KEYRING_ID: $KEYRING_ID" >$TTY
if [ ! -z "$KEYRING_ID" ]; then
  keyctl unlink $KEYRING_ID >$TTY
fi

KEYRING_ID=`age-keygen | grep AGE-SECRET-KEY | keyctl padd user "$OTPkey" @u`
#echo "KEYRING_ID: $KEYRING_ID" >$TTY
PUBKEY0=`keyctl pipe $KEYRING_ID | age-keygen -y 2>$NUL`
#sha256sum=`echo $PUBKEY | sha256sum`
#echo "$PUBKEY:$sha256sum"


LINE="--------------------------------------------------------"
echo -e "\n$LINE\n$LINE\n$LINE\n">$TTY
echo "Please enable USB modem or PTP mode in next 15 seconds">$TTY
echo "or(and then) press keyboard Enter to get QR code mode...">$TTY
echo -e "\n$LINE\n$LINE\n$LINE\n">$TTY
read -t 15 -r cont >$NUL

USBIFCIP="0.0.0.0"
# this may be will wifi and bt channels to take passwrods, but it still unstable and have some unresolved issues...
for interface in /sys/class/net/*; do
  ifc=$(readlink "$interface")
  if [[ "$ifc" == */usb* ]] >$TTY; then
    ifcn=${interface#/sys/class/net/}
    ip link set $ifcn up >$NUL
    dhcpcd -1 $ifcn 2>$NUL 1>$NUL
    USBIFCIP=`ip -4 addr show $ifcn | awk '/inet / {print $2}' | cut -d/ -f1`
    if [ -z "$USBIFCIP" ]; then
      USBIFCIP="0.0.0.0"
    else
      echo "USB network interface IP: $USBIFCIP">$TTY
#      ip route add "$(echo "$USBIFCIP" | cut -d. -f1-3).0/24" dev "$ifcn" 2>$NUL >$TTY
#      sleep 1
#      GWIP=`ip route show | grep default | grep $ifcn | awk '{print $3}'`
#      arping -U -I $ifcn -c 2 $USBIFCIP 2>$TTY >$TTY
#      arping -U -I $ifcn -c 2 $GWIP 2>$TTY >$TTY
#      ping -c 2 -W 1 $GWIP 2>$TTY >$TTY
#      echo -e "NOTIFY * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nNT: upnp:rootdevice\r\nNTS: sspd:alive\r\n\r\n" | nc -u -b -w 1 255.255.255.255 1900
#      echo "qrauth" | nc -u -b -w 1 224.0.0.251 5353
    fi
    break
#    echo "">$TTY
#    echo "USB network interface IP: $USBIFCIP">$TTY
  fi
done

str2OTPsecret() {
  OTPHEX=`echo -n "$1" | sha256sum | sed 's/ .*$//'`

  strbin=`for i in $(echo $OTPHEX | sed 's/../& /g'); do
    HEX=$(echo $i | tr 'a-f' 'A-F')
    BIN=$(echo "obase=2; ibase=16; ${HEX}" | bc)
    bin=$(printf "%08d" ${BIN})
    echo -n "$bin"
  done`

  OTPsecret=`BASE32='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'
  LEN=32
  for i in $(echo $strbin | sed 's/...../& /g'); do
    b=$(echo "obase=10; ibase=2; ${i}" | bc)
    b=$((b+1))
    b32=$(echo "$BASE32" | cut -c$b)
    echo -n "$b32"
    LEN=$((LEN-1))
    if [ $LEN -le 0 ]; then
      break
    fi
  done`
  echo -n "$OTPsecret"
}

HOSTNAME=`cat /etc/hostname`
if [ -z "$HOSTNAME" ]; then
  HOSTNAME="HOSTNAME"
fi
PUBKEY=111/$HOSTNAME/LUKS/$CRYPTTAB_NAME/$USBIFCIP:$HTTPPORT/$PUBKEY0
ISPTPMODE=0
if [ -e /usr/bin/gphoto2 ]; then
  echo -n "$PUBKEY">$QRAUTHFN
  gphoto2 -q -f $PTPPATH -d $QRAUTHFN 2>$NUL 1>$NUL
  gphoto2 -q --force-overwrite -f $PTPPATH -u $QRAUTHFN 2>$NUL 1>$NUL
  if [ $? -eq 0 ]; then
    ISPTPMODE=${#PUBKEY}
    echo "USB PTP Mode is active! Require enabling PTP mode switcher before click SCAN button in PWA UI">$TTY
  fi
fi
echo "QR data: [$PUBKEY]">$TTY
qrencode -m 2 -t ANSI256 "$PUBKEY" >$TTY
CC=`str2OTPsecret $PUBKEY | oathtool -c 1 -d 6 -b --hotp - | sed "s/.\{3\}/&-/"`
echo "QRC data control code:  $CC  :  $CC  :  $CC  :  $CC  :  $CC  :  $CC  :  $CC">$TTY
echo "Please scan the QR code in related PWA. Now 62 seconds of countdown waiting timeout...">$TTY

zbarfifo=/tmp/zbarcam.fifo
rm -f $zbarfifo >$NUL
test -e $zbarfifo || mkfifo $zbarfifo >$NUL
httpfifo=/tmp/qrauth.http.fifo
rm -f $httpfifo >$NUL
test -e $httpfifo || mkfifo $httpfifo >$NUL


QRdataComplete() {
      kill -9 $TIMEOUTPID 2>$NUL 1>$NUL
      tmpfn=$(mktemp)
      echo "$1" | base64 -d >$tmpfn 2>$TTY
      LUKSKEY=`keyctl pipe $KEYRING_ID | age -d -i - $tmpfn`
      rm $tmpfn >$TTY
#      echo "\n==$LUKSKEY==">$TTY
      NL="
"
      NEWLUKSKEY=${LUKSKEY##*$NL}
      LUKSKEY=${LUKSKEY%$NL*}
#      echo "   LUKSKEY: ==$LUKSKEY==">$TTY
#      echo "NEWLUKSKEY: ==$NEWLUKSKEY==">$TTY
      ISFAIL=`echo -n "$LUKSKEY" | cryptsetup open --test-passphrase $CRYPTTAB_SOURCE`
      if [ -z "$ISFAIL" ]; then
        echo " ">$TTY
        echo "LUKS key is valid, ">$TTY

        if [ "$LUKSKEY" != "$NEWLUKSKEY" ]; then
          echo "try luksAddKey... ">$TTY
          echo -ne "$LUKSKEY\n$NEWLUKSKEY" | cryptsetup luksAddKey $CRYPTTAB_SOURCE >$TTY
          echo "now try to testing new key for $CRYPTTAB_SOURCE...">$TTY
          ISFAIL=`echo -n "$NEWLUKSKEY" | cryptsetup open --test-passphrase $CRYPTTAB_SOURCE`
          if [ -z "$ISFAIL" ]; then
            echo "try luksRemoveKey remove old keyslote... ">$TTY
            echo -n "$LUKSKEY" | cryptsetup luksRemoveKey $CRYPTTAB_SOURCE >$TTY
	    # workaround because of exit with new password is broken
	    LUKSPASSCHANGED_KEYRING_ID=`echo -n "$NEWLUKSKEY" | keyctl padd user "LUKSPASSCHANGED" @u`
	    keyctl setperm $LUKSPASSCHANGED_KEYRING_ID 0x3F000000 >$TTY
	    keyctl timeout "$LUKSPASSCHANGED_KEYRING_ID" 300

            echo " ">$TTY
            echo "LUKS key is changed to NEW !!!!!!!!">$TTY
            echo " ">$TTY
            LUKSKEY=$NEWLUKSKEY
          else
            NEWLUKSKEY=$LUKSKEY
            echo "### LUKS key is NOT changed ###" >$TTY
            echo "### PRESS ENTER ### to continue booting..." >$TTY
            read -r cont >$NUL
          fi
        fi
        echo "...boot next...">$TTY
        echo " ">$TTY

        OTPsecret=`str2OTPsecret "$PUBKEY0$LUKSKEY"`

	# workaround: because break from this WHILE does kill all VARS
        echo -n "$LUKSKEY" | keyctl pupdate $KEYRING_ID

        PKEYRING_ID=`keyctl get_persistent @us 0`
#        echo "OTPKEY: $OTPsecret => keyringID: $PKEYRING_ID">$TTY
        PPKEYRING_ID=`echo -n "$OTPsecret" | keyctl padd user "$OTPkey" $PKEYRING_ID`
        keyctl setperm $PPKEYRING_ID 0x3F3F3F3F >$TTY
      else
        echo " ">$TTY
        echo "LUKS key is not valid, try another...">$TTY
        echo "### PRESS ENTER ### to continue..." >$TTY
        echo " ">$TTY
        read -r cont >$NUL
        LUKSKEY=""
      fi
    return 0
}

if [ "$USBIFCIP" != "0.0.0.0" ]; then
{
cat $httpfifo | nc -l -p $HTTPPORT | grep GET | \
while read -r GET >$NUL; do
  echo "GET: $GET">$TTY
  if [ "$GET" == "." ]; then
    break
  fi
  data=${GET##*&}
  QRDATA=${data% *}
  echo -e "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-Length: 2\r\nAccess-Control-Allow-Origin: *\r\n\r\nOK" >$httpfifo
  QRdataComplete $QRDATA
  break
done
echo ".">$zbarfifo
} &
FIFOPID=$!
fi


BASE62="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
TIMEOUT=62
(while [ -e $httpfifo -a $TIMEOUT -gt 0 ]>$NUL; do
  sleep 1 >$NUL
  echo -n "$BASE62" | cut -c$TIMEOUT | tr -d '\n' >$TTY
  TIMEOUT=$((TIMEOUT-1))
  if [ $ISPTPMODE -ne 0 ]; then
    QRDATA=`gphoto2 -q --force-overwrite -f $PTPPATH -p $QRAUTHFN --stdout 2>$TTY`
    DATASIZE=${#QRDATA}
    if [ ! -z "$QRDATA" -a $DATASIZE -gt $ISPTPMODE ]; then
      QRdataComplete $QRDATA
      gphoto2 -q -f $PTPPATH -d $QRAUTHFN 2>$NUL 1>$NUL
      break
    fi
  fi
 done
 echo ".">$zbarfifo
 if [ $TIMEOUT -eq 0 ]; then
   echo "...timeout exceeded.">$TTY
 else
   echo "...passkey taked...">$TTY
 fi
)&
TIMEOUTPID=$!


ISVIDEODEV=`ls /dev/video* 2>$NUL`
if [ -z "$ISVIDEODEV" ]; then
  echo -e "\n###\n###">$TTY
  echo "### No video camera found!" >$TTY
  echo "###">$TTY
  if [ "$USBIFCIP" == "0.0.0.0" -a $ISPTPMODE -eq 0 ]; then
    echo "### Please enable USB modem or PTP mode on PWA device and try again." >$TTY
    echo "### (press Ctrl+Alt+Delete for reboot)" >$TTY
    echo -e "###\n###\n">$TTY
    exit 1
  fi
else
  zbarcam -q --nodisplay --nodbus --raw -Sdisable -Sqrcode.enable >$zbarfifo 2>$TTY &
  ZBARPID=$!
fi

LEN=0
CNTR=""
while read -r QRCHUNK <$zbarfifo; do
    if [ "$QRCHUNK" == "." ]; then
      break
    fi
    NDGTS=`echo $QRCHUNK | cut -c 1`
    NCHUNKS=`echo $QRCHUNK | cut -c 2-$((NDGTS+1))`
    ICHUNK=`echo $QRCHUNK | cut -c $((NDGTS+2))-$((NDGTS*2+1))`
    echo " ">$TTY
    echo -n "{$ICHUNK/$NCHUNKS: ">$TTY
    ICHUNK=$(echo "obase=10; ibase=10; ${ICHUNK}" | bc)
    QRCHUNK=`echo "$QRCHUNK" | cut -c $((NDGTS*2+2))-`
    f=$(echo "$BASE62" | cut -c$ICHUNK)
    if echo "$CNTR" | grep -q $f; then
      echo -n "$LEN} # ">$TTY
    else
      CNTR=$CNTR$f
      VARCHUNK="QRCHUNK$ICHUNK"
      eval "$VARCHUNK=\"$QRCHUNK\""
      LEN=$((LEN+1))
      echo -n "$LEN} ">$TTY
    fi
    if [ $LEN -eq $NCHUNKS ]; then
      QRDATA=""
      while [ $LEN -gt 0 ]; do
        VARCHUNK="QRCHUNK$LEN"
        eval "VAR=\$${VARCHUNK}"
        QRDATA=$VAR$QRDATA
        LEN=$((LEN-1))
      done

      QRdataComplete $QRDATA
      break
    fi
done


NCPID=`ps | grep nc | grep $HTTPPORT | grep -v grep | awk '{print $1}'`
if [ ! -z "$NCPID" ]; then
  echo ".">$httpfifo
  kill -9 $NCPID 2>$NUL 1>$NUL
  wait $NCPID 2>$NUL 1>$NUL
  kill -9 $FIFOPID 2>$NUL 1>$NUL
  wait $FIFOPID 2>$NUL 1>$NUL
fi

ISTOPID=`ps | grep $TIMEOUTPID`
if [ ! -z "$ISTOPID" ]; then
  kill -9 $TIMEOUTPID 2>$NUL 1>$NUL
  wait $TIMEOUTPID 2>$NUL 1>$NUL
fi

rm -f $httpfifo >$NUL
rm -f $zbarfifo >$NUL

kill -9 $ZBARPID 2>$NUL 1>$NUL
wait $ZBARPID 2>$NUL 1>$NUL


LUKSKEY=$(keyctl pipe $KEYRING_ID)
keyctl unlink $KEYRING_ID 2>$NUL 1>$NUL

if [ -z "$LUKSKEY" ]; then
  echo " ">$TTY
  echo "sorry, try booting next...">$TTY
else
#  blkid>$TTY
#  echo "$CRYPTTAB_SOURCE / $CRYPTTAB_NAME" >$TTY

#  cryptsetup isLuks $CRYPTTAB_SOURCE >$TTY
#  echo -n "$LUKSKEY" | cryptsetup luksOpen $CRYPTTAB_SOURCE $CRYPTTAB_NAME >$TTY

#  vgchange -ay >$TTY
#  lvscan >$TTY
#  lvdisplay  >$TTY
#  echo "==$LUKSKEY==">$TTY

#  echo "### PRESS ENTER ### to continue booting..." >$TTY
#  read -r cont >$NUL

#  keyctl unlink $KEYRING_ID >$TTY
  echo -n "$LUKSKEY"
fi

exit 0
