#!/bin/sh
# location path: /usr/local/sbin
# in /etc/rc.local must execute keyctl link $(keyctl show @us | grep TOTPKEY | awk '{print $1}') @s

#set +e

PACKAGE_NAME="cryptkey-from-qrcode"
TTY=/dev/tty0
#TTY=/dev/stderr
OTPkey="TOTPKEY"

# workaround because of changing passsword for LUKS disk not working properly inner this script
LUKSPASSCHANGED_KEYRING_ID=`keyctl search @u user "LUKSPASSCHANGED" 2>/dev/null`
if [ ! -z "$LUKSPASSCHANGED_KEYRING_ID" ]; then
  keyctl pipe $LUKSPASSCHANGED_KEYRING_ID
  keyctl unlink $LUKSPASSCHANGED_KEYRING_ID >$TTY
  exit 0
fi

KEYRING_ID=`keyctl search @u user "$OTPkey" 2>/dev/null`
#echo "KEYRING_ID: $KEYRING_ID" >$TTY
if [ ! -z "$KEYRING_ID" ]; then
  keyctl unlink $KEYRING_ID >$TTY
fi

KEYRING_ID=`age-keygen | grep AGE-SECRET-KEY | keyctl padd user "$OTPkey" @u`
#echo "KEYRING_ID: $KEYRING_ID" >$TTY
PUBKEY=`keyctl pipe $KEYRING_ID | age-keygen -y`
#sha256sum=`echo $PUBKEY | sha256sum`
#echo "$PUBKEY:$sha256sum"

HOSTNAME=`cat /etc/hostname`
if [ -z "$HOSTNAME" ]; then
  HOSTNAME="HOSTNAME"
fi
PUBKEY="111/$HOSTNAME/LUKS/sdb3_qrcode/$PUBKEY"
echo "$PUBKEY">$TTY

echo " ">$TTY
qrencode -t ANSI256 "$PUBKEY" 2>&1 >$TTY
echo "Please scan the public key QRcode and return in the webcam the enrypted password...">$TTY
echo "and now 62 seconds of countdown timeout...">$TTY

BASE62="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
LEN=0
CNTR=""
TIMEOUT=62

(while [ $TIMEOUT -gt 0 ]; do sleep 1; echo -n $(echo "$BASE62" | cut -c$TIMEOUT) >$TTY; TIMEOUT=$((TIMEOUT-1)); done;
keyctl unlink $KEYRING_ID>/dev/null;
kill -2 $(ps | grep zbarcam | awk '{print $1}') >/dev/null)&
TIMEOUTPID=$!

zbarcam -q --nodisplay --nodbus --raw -Sdisable -Sqrcode.enable | \
while read -r QRCHUNK >/dev/null; do
    NDGTS=`echo $QRCHUNK | cut -c 1`
    NCHUNKS=`echo $QRCHUNK | cut -c 2-$((NDGTS+1))`
    ICHUNK=`echo $QRCHUNK | cut -c $((NDGTS+2))-$((NDGTS*2+1))`
    echo " ">$TTY
    echo -n "{$ICHUNK/$NCHUNKS: ">$TTY
    ICHUNK=$(echo "obase=10; ibase=10; ${ICHUNK}" | bc)
    QRCHUNK=`echo "$QRCHUNK" | cut -c $((NDGTS*2+2))-`
    f=$(echo "$BASE62" | cut -c$ICHUNK)
    if echo "$CNTR" | grep -q $f; then
      echo -n "$LEN} # ">$TTY
    else
      CNTR=$CNTR$f
      VARCHUNK="QRCHUNK$ICHUNK"
      eval "$VARCHUNK=\"$QRCHUNK\""
      LEN=$((LEN+1))
      echo -n "$LEN} ">$TTY
    fi
    if [ $LEN -eq $NCHUNKS ]; then
      QRDATA=""
      while [ $LEN -gt 0 ]; do
        VARCHUNK="QRCHUNK$LEN"
        eval "VAR=\$${VARCHUNK}"
        QRDATA=$VAR$QRDATA
        LEN=$((LEN-1))
      done

      kill -9 $TIMEOUTPID 2>&1 >/dev/null
      tmpfn=$(mktemp)
      echo "$QRDATA" | base64 -d >$tmpfn 2>$TTY
      LUKSKEY=`keyctl pipe $KEYRING_ID | age -d -i - $tmpfn`
      rm $tmpfn >$TTY
#      echo "\n==$LUKSKEY==">$TTY
      NL="
"
      NEWLUKSKEY=${LUKSKEY##*$NL}
      LUKSKEY=${LUKSKEY%$NL*}
#      echo "   LUKSKEY: ==$LUKSKEY==">$TTY
#      echo "NEWLUKSKEY: ==$NEWLUKSKEY==">$TTY
      ISFAIL=`echo -n "$LUKSKEY" | cryptsetup open --test-passphrase $CRYPTTAB_SOURCE 2>&1`
      if [ -z "$ISFAIL" ]; then
        echo " ">$TTY
        echo "LUKS key is valid, ">$TTY

        if [ "$LUKSKEY" != "$NEWLUKSKEY" ]; then
          echo "try luksAddKey... ">$TTY
          echo -ne "$LUKSKEY\n$NEWLUKSKEY" | cryptsetup luksAddKey $CRYPTTAB_SOURCE 2>&1 >$TTY
          echo "now try to testing new key for $CRYPTTAB_SOURCE...">$TTY
          ISFAIL=`echo -n "$NEWLUKSKEY" | cryptsetup open --test-passphrase $CRYPTTAB_SOURCE 2>&1`
          if [ -z "$ISFAIL" ]; then
            echo "try luksRemoveKey remove old keyslote... ">$TTY
            echo -n "$LUKSKEY" | cryptsetup luksRemoveKey $CRYPTTAB_SOURCE 2>&1 >$TTY
	    # workaround because of exit with new password is broken
	    LUKSPASSCHANGED_KEYRING_ID=`echo -n "$NEWLUKSKEY" | keyctl padd user "LUKSPASSCHANGED" @u`
	    keyctl setperm $LUKSPASSCHANGED_KEYRING_ID 0x3F000000 >$TTY
	    keyctl timeout "$LUKSPASSCHANGED_KEYRING_ID" 300

            echo " ">$TTY
            echo "LUKS key is changed to NEW !!!!!!!!">$TTY
            echo " ">$TTY
            LUKSKEY=$NEWLUKSKEY
          else
            NEWLUKSKEY=$LUKSKEY
            echo "### LUKS key is NOT changed ###" >$TTY
            echo "### PRESS ENTER ### to continue booting..." >$TTY
            read -r cont >/dev/null
          fi
        fi
        echo "...boot next...">$TTY
        echo " ">$TTY

        OTPHEX=`echo -n "$LUKSKEY" | sha256sum | sed 's/ .*$//'`

        strbin=`for i in $(echo $OTPHEX | sed 's/../& /g'); do
          HEX=$(echo $i | tr 'a-f' 'A-F')
          BIN=$(echo "obase=2; ibase=16; ${HEX}" | bc)
          bin=$(printf "%08d" ${BIN})
          echo -n "$bin"
        done`

        OTPsecret=`BASE32='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'
        LEN=32
        for i in $(echo $strbin | sed 's/...../& /g'); do
          b=$(echo "obase=10; ibase=2; ${i}" | bc)
          b=$((b+1))
          b32=$(echo "$BASE32" | cut -c$b)
          echo -n "$b32"
          LEN=$((LEN-1))
          if [ $LEN -le 0 ]; then
            break
          fi
        done`

	# workaround: because break from this WHILE does kill all VARS
        echo -n "$LUKSKEY" | keyctl pupdate $KEYRING_ID

        PKEYRING_ID=`keyctl get_persistent @us 0`
        echo "OTPKEY keyringID: $PKEYRING_ID">$TTY
        PPKEYRING_ID=`echo -n "$OTPsecret" | keyctl padd user "$OTPkey" $PKEYRING_ID`
        keyctl setperm $PPKEYRING_ID 0x3F3F3F3F >$TTY
      else
        echo " ">$TTY
        echo "LUKS key is not valid, try another...">$TTY
        echo "### PRESS ENTER ### to continue..." >$TTY
        echo " ">$TTY
        read -r cont >/dev/null
        LUKSKEY=""
      fi
      kill -2 $(ps | grep zbarcam | awk '{print $1}') 2>&1 >/dev/null
      break
    fi

done

LUKSKEY=$(keyctl pipe $KEYRING_ID)
keyctl unlink $KEYRING_ID>/dev/null

if [ -z "$LUKSKEY" ]>/dev/null; then
  echo " ">$TTY
  echo "sorry, try booting next...">$TTY
else
#  blkid>$TTY
#  echo "$CRYPTTAB_SOURCE / $CRYPTTAB_NAME" >$TTY

#  cryptsetup isLuks $CRYPTTAB_SOURCE >$TTY
#  echo -n "$LUKSKEY" | cryptsetup luksOpen $CRYPTTAB_SOURCE $CRYPTTAB_NAME >$TTY

#  vgchange -ay >$TTY
#  lvscan >$TTY
#  lvdisplay  >$TTY
#  echo "==$LUKSKEY==">$TTY

#  echo "### PRESS ENTER ### to continue booting..." >$TTY
#  read -r cont >/dev/null

#  keyctl unlink $KEYRING_ID >$TTY
  echo -n "$LUKSKEY"
fi

exit 0
