#!/bin/sh
# location path: /usr/local/sbin
# in /etc/rc.local must execute keyctl link $(keyctl show @us | grep TOTPKEY | awk '{print $1}') @s

#set +e

# package infos  by ALPX
VERSION="1.3"
PACKAGE_NAME="cryptkey-from-qrcode"
TTY=/dev/tty0
#TTY=/dev/stdout
OTPkey="TOTPKEY"

#KEYRING_ID=`keyctl newring my_session_keyring @s`
#keyctl add user $PUBKEY "$SECKEY" "$KEYRING_ID"
#age-keygen 2>&1 | tail -2 | sed 's/^.*key: //' | tr '\n' ' '
KEYRING_ID=`keyctl search @u user "$OTPkey" 2>/dev/null`
#echo "KEYRING_ID: $KEYRING_ID" >$TTY
if [ ! -z "$KEYRING_ID" ]; then
  keyctl unlink $KEYRING_ID >$TTY
fi

KEYRING_ID=`age-keygen | grep AGE-SECRET-KEY | keyctl padd user "$OTPkey" @u`
#echo "KEYRING_ID: $KEYRING_ID" >$TTY
PUBKEY=`keyctl pipe $KEYRING_ID | age-keygen -y`
#sha256sum=`echo $PUBKEY | sha256sum`
#echo "$PUBKEY:$sha256sum"

HOSTNAME=`cat /etc/hostname`
if [ -z "$HOSTNAME" ]; then
  HOSTNAME="HOSTNAME"
fi
#HNC=${#HOSTNAME}
PUBKEY="111/$HOSTNAME/LUKS/sdb3_qrcode/$PUBKEY"
echo "$PUBKEY">$TTY

echo " ">$TTY
qrencode -t ANSI256 "$PUBKEY" 2>&1 >$TTY

QRCODEPATH=/tmp/qrcode.bmp
touch $QRCODEPATH >$TTY

#ffmpeg .. -pix_fmt rgb24 -window_size 80x25 -f caca -
#ffmpeg .. -pix_fmt bgra -xoffset 500 -f fbdev /dev/fb0
#ffmpeg -loglevel quiet -hide_banner -y -f v4l2 -i /dev/video0 -r 2.0 -update 1 -vf "extractplanes=y,crop=800:720:200:0" $QRCODEPATH 2>&1 >$TTY &
ffmpeg -loglevel quiet -hide_banner -y -f v4l2 -i /dev/video0 -r 4.0 -update 1 \
 -vf "extractplanes=y,crop=800:720:200:0,scale=400:360" $QRCODEPATH 2>&1 >$TTY &
ffpid=$!

#terminate() {
#  kill -s SIGQUIT $ffpid
#  exec /lib/cryptsetup/askpass "Enter passphrase for $CRYPTTAB_NAME ($CRYPTTAB_SOURCE): "
#  exit 0
#}
#trap terminate INT TERM
# TODO: TODO: TODO:  should make universal qrcode chunks parsing..
BASE62="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
LEN=0
CNTR=""
TIMEOUT=240
#KEYPRESSED=""
#while [ -z "$KEYPRESSED" ];
while [ $TIMEOUT -gt 0 ];
do
  inotifywait -qqe 'close' -t 3 $QRCODEPATH 2>&1 >/dev/null

  QRCHUNK=`zbarimg -q --nodbus --raw $QRCODEPATH`
  if [ ! -z "$QRCHUNK" ]; then
#    TIMEOUT=30
    NDGTS=`echo $QRCHUNK | cut -c 1`
    NCHUNKS=`echo $QRCHUNK | cut -c 2-$((NDGTS+1))`
    ICHUNK=`echo $QRCHUNK | cut -c $((NDGTS+2))-$((NDGTS*2+1))`
    echo " ">$TTY
    echo -n "{$ICHUNK/$NCHUNKS: ">$TTY
    ICHUNK=$(echo "obase=10; ibase=10; ${ICHUNK}" | bc)
    QRCHUNK=`echo "$QRCHUNK" | cut -c $((NDGTS*2+2))-`
    f=$(echo "$BASE62" | cut -c$ICHUNK)
    if echo "$CNTR" | grep -q $f; then
      echo -n "$LEN} # ">$TTY
    else
      CNTR=$CNTR$f
      VARCHUNK="QRCHUNK$ICHUNK"
      eval "$VARCHUNK=\"$QRCHUNK\""
      LEN=$((LEN+1))
      echo -n "$LEN} ">$TTY
    fi
    if [ $LEN -eq $NCHUNKS ]; then
      QRDATA=""
      while [ $LEN -gt 0 ]; do
        VARCHUNK="QRCHUNK$LEN"
        eval "VAR=\$${VARCHUNK}"
        QRDATA=$VAR$QRDATA
        LEN=$((LEN-1))
      done

      echo "$QRDATA" | base64 -d >$QRCODEPATH.dat

      LUKSKEY=`keyctl pipe $KEYRING_ID | age -d -i - $QRCODEPATH.dat`
#      echo "\n==$LUKSKEY==">$TTY
#      TIMEOUT=0
      kill -3 $ffpid >/dev/null
      ffpid=0
      TIMEOUT=0
#      KEYPRESSED="NO"
      NL="
"
      NEWLUKSKEY=${LUKSKEY##*$NL}
      LUKSKEY=${LUKSKEY%$NL*}
#      echo "   LUKSKEY: ==$LUKSKEY==">$TTY
#      echo "NEWLUKSKEY: ==$NEWLUKSKEY==">$TTY
      ISFAIL=`echo -n "$LUKSKEY" | cryptsetup open --test-passphrase $CRYPTTAB_SOURCE 2>&1`
      if [ -z "$ISFAIL" ]; then
        echo " ">$TTY
        echo "LUKS key is valid, ">$TTY

        if [ "$LUKSKEY" != "$NEWLUKSKEY" ]; then
#          ISFAIL=`echo "$NEWLUKSKEY" | cryptsetup luksChangeKey $CRYPTTAB_SOURCE --key-slot 0`
          echo "try luksAddKey... ">$TTY
          echo -ne "$LUKSKEY\n$NEWLUKSKEY" | cryptsetup luksAddKey $CRYPTTAB_SOURCE 2>&1 >$TTY
          echo "now try to testing new key for $CRYPTTAB_SOURCE...">$TTY
          ISFAIL=`echo -n "$NEWLUKSKEY" | cryptsetup open --test-passphrase $CRYPTTAB_SOURCE 2>&1`
          if [ -z "$ISFAIL" ]; then
            echo "try luksRemoveKey remove old keyslote... ">$TTY
            echo -n "$LUKSKEY" | cryptsetup luksRemoveKey $CRYPTTAB_SOURCE 2>&1 >$TTY
            echo "try reset all disk caches... ">$TTY
	    sync >/dev/null
	    blockdev --flushbufs $CRYPTTAB_SOURCE 2>&1 >$TTY
	    blockdev --rereadpt $CRYPTTAB_SOURCE 2>&1 >$TTY
	    echo 3 > /proc/sys/vm/drop_caches
	    udevadm settle
	    sleep 1 >/dev/null

            echo " ">$TTY
            echo "LUKS key is changed to NEW !!!!!!!!">$TTY
            echo " ">$TTY
            LUKSKEY=$NEWLUKSKEY
          else
            NEWLUKSKEY=$LUKSKEY
            echo "### LUKS key is NOT changed ###" >$TTY
            echo "### PRESS ENTER ### to continue booting..." >$TTY
            read -r cont >/dev/null
          fi
        fi
        echo "...boot next...">$TTY
        echo " ">$TTY

        OTPHEX=`echo -n "$LUKSKEY" | sha256sum | sed 's/ .*$//'`

        strbin=`for i in $(echo $OTPHEX | sed 's/../& /g'); do
          HEX=$(echo $i | tr 'a-f' 'A-F')
          BIN=$(echo "obase=2; ibase=16; ${HEX}" | bc)
          bin=$(printf "%08d" ${BIN})
          echo -n "$bin"
        done`

        OTPsecret=`BASE32='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'
        LEN=32
        for i in $(echo $strbin | sed 's/...../& /g'); do
          b=$(echo "obase=10; ibase=2; ${i}" | bc)
          b=$((b+1))
          b32=$(echo "$BASE32" | cut -c$b)
          echo -n "$b32"
          LEN=$((LEN-1))
          if [ $LEN -le 0 ]; then
            break
          fi
        done`

        keyctl unlink $KEYRING_ID >$TTY
        PKEYRING_ID=`keyctl get_persistent @us 0`
        echo "OTPKEY keyringID: $PKEYRING_ID">$TTY
        PPKEYRING_ID=`echo -n "$OTPsecret" | keyctl padd user "$OTPkey" $PKEYRING_ID`
#        keyctl add user "$OTPkey" "$OTPsecret" $PKEYRING_ID 2>&1 >$TTY
#        echo "OTPKEY: $OTPsecret">$TTY
        keyctl setperm $PPKEYRING_ID 0x3F3F3F3F >$TTY
      else
        echo " ">$TTY
        echo "LUKS key is not valid, try another...">$TTY
        echo " ">$TTY
        TIMEOUT=240
        QRCHUNK1=""
        QRCHUNK2=""
        QRCHUNK3=""
        QRCHUNK4=""
        LUKSKEY=""
      fi
    fi
#    ffmpeg -nostdin -loglevel quiet -hide_banner -i $QRCODEPATH -pix_fmt bgra -f fbdev /dev/fb0 >/dev/null
# some issue with showing on fb0, booting hangs
    QRCHUNK=""
  fi

  TIMEOUT=$((TIMEOUT-1))
  echo -n ".">$TTY
#  echo -n "$TIMEOUT..">$TTY
#  if [ $TIMEOUT -le 0 ]; then
#    read -t 1 -n 1 -s KEYPRESSED >/dev/null
#    TIMEOUT=10
#  fi
done

if [ $ffpid -gt 0 ]>/dev/null; then
  kill -3 $ffpid >/dev/null
  sleep 1 >/dev/null
fi

if [ -z "$LUKSKEY" ]>/dev/null; then
#  exec /lib/cryptsetup/askpass "Try enter passphrase manually for $CRYPTTAB_NAME ($CRYPTTAB_SOURCE): "
  echo " ">$TTY
  echo "sorry, try booting next...">$TTY
else

#  blkid>$TTY
#  echo "$CRYPTTAB_SOURCE / $CRYPTTAB_NAME" >$TTY

#  cryptsetup isLuks $CRYPTTAB_SOURCE >$TTY
#  echo -n "$LUKSKEY" | cryptsetup luksOpen $CRYPTTAB_SOURCE $CRYPTTAB_NAME >$TTY

#  vgchange -ay >$TTY
#  lvscan >$TTY
#  lvdisplay  >$TTY
#  echo "==$LUKSKEY==">$TTY

#  echo "### PRESS ENTER ### to continue booting..." >$TTY
#  read -r cont >/dev/null

#  keyctl unlink $KEYRING_ID >$TTY
  echo -n "$LUKSKEY"
fi


exit 0
