let lsHSD = 'hst/svc/dst'; // hostName/serviceName/destinationName
let emtyHSdst = {
  currentKey: '',
  previousKey: '',
  applyNewKey: ''
}
let objHSD = { // object description
  hostName1: {
    serviceName1: {
      destinationName1: emtyHSdst
    },
  }
}
let lsSelectedHSD = 'selectedHSD';
let selectedHSD = undefined;
let lsKeysHistoryPrefix = 'keysHistory: ';

function YYYYMMDDHHmmSS() {
  let ts = new Date();
  function n2(n) {return ('0' + n.toString()).slice(-2)}
  return ts.getFullYear().toString() + n2(ts.getMonth()+1) + n2(ts.getDate())
      + n2(ts.getHours()) + n2(ts.getMinutes()) + n2(ts.getSeconds());
}
function prepareControls() {

  let colorHighlightSuccess = $('.bg-success-highlight').css('background-color');
  let progressBar = $('#progressBar');
  let btnShowCurrentPassword = $('#btnShowCurrentPassword');
  let btnShowNewPassword = $('#btnShowNewPassword');

  let cardArea = $('#cardArea');
  let labelOTPcode = $('#labelOTPcode');
  let inpCurrentPassword = $('#inpCurrentPassword');
  let inpNewPassword = $('#inpNewPassword');
  let btnClearKeyDestination = $('#btnClearKeyDestination');
  let btnSaveNewPassword = $('#btnSaveNewPassword');
  let btnClearNewPassword = $('#btnClearNewPassword');
  let btnGenerateNewPassword = $('#btnGenerateNewPassword');
  let btnScanSessionPubkey = $('#btnScanSessionPubkey');
  let btnRevertPreviousPassword = $('#btnRevertPreviousPassword');
  let btnClearPassword = $('#btnClearPassword');
  let btnAutoGenerateNewPassword = $('#btnAutoGenerateNewPassword');
  //let lblQrCreate = $('#lblQrCreate');
  //let lblQrShow = $('#lblQrShow');
  //let lblScanQrCode = $('#lblScanQrCode');
  let btnShowQrCode = $('#btnShowQrCode');
  let btnKeyDestList = $('#btnKeyDestList');
  let selHSD = $('#selHstSrvDst');
  let settingsArea = $('#settingsArea');
  let btnSettings = $('#btnSettings');
  let btnShowHelp = $('#btnShowHelp');
  let whatTheArea = $('#whatTheArea');
  let switcherPTPMode = $('#switcherPTPMode');
  let hsdHtmlTemplate = '<li id="#id"><a class="dropdown-item text-body" href="#">#html</a></li>';
  let hsdHtmlTemplateBtn = '<button id="#id" class="dropdown-item ms-2 text-warning" data-bs-target="#openSaveFileArea">#html</button>';
  let miOpenSave = '<span class="text-danger">Open</span>/<span class="text-success">Save</span> file...';
  let bgColorSuccess = $('.bg-success').css('backgroundColor');

  function flashDestList() {
    btnKeyDestList.addClass('btn-outline-success bg-success-highlight');
    setTimeout(function () {
      btnKeyDestList.removeClass('btn-outline-secondary bg-success-highlight');
    },500);
  }
  selHSD.html('');
  let isHSDnotEmpty = false;
  if (localStorage[lsHSD]) {
    objHSD = JSON.parse(localStorage[lsHSD]);
    for (let hst in objHSD)
      for (let svc in objHSD[hst])
        for (let dst in objHSD[hst][svc]) {
          let dest = hst+'/'+svc+'/'+dst;
          let html = hsdHtmlTemplate.replace('#id', dest.replaceAll('/','_')).replace('#html',dest);
          if (svc.replace(/luks|crypttab|initramfs/i, '!') === '!')
            html = html.replace('text-body', 'text-success');
          selHSD.append(html);
          isHSDnotEmpty = true;
        }
    if (!isHSDnotEmpty)
      localStorage.removeItem(lsHSD);
  } else
    objHSD = {};
  if (isHSDnotEmpty) {
    flashDestList()
    selHSD.append('<li><hr class="dropdown-divider"></li>');
    selHSD.append(hsdHtmlTemplateBtn.replace('#id', 'actOpenSaveFile').replace('#html', miOpenSave));
  }
  btnAutoGenerateNewPassword.click(function () {
    event.preventDefault();
    if (selectedHSD && inpKeyDest.val()) {
      console.log(selectedHSD);
      selectedHSD['newKeyIsAutoGenerated'] = !selectedHSD['newKeyIsAutoGenerated'];
      if (selectedHSD.newKeyIsAutoGenerated) {
        btnAutoGenerateNewPassword.addClass('text-success-highlight');
        btnGenerateNewPassword.addClass('bg-success');
      }
      localStorage[lsHSD] = JSON.stringify(objHSD);
    } else
      flashDestList();
  });

  function fillPasswordInputs(hsd) {
    inpCurrentPassword.val(hsd['currentKey'] ? hsd['currentKey'] : '');
    if (hsd['previousKey'] && hsd['previousKey'] !== hsd['currentKey'])
      btnRevertPreviousPassword.removeClass('d-none');
    inpNewPassword.val(hsd['applyNewKey'] ? hsd['applyNewKey'] : '');
    btnSaveNewPassword[hsd['applyNewKey'] ? 'addClass' : 'removeClass']('bg-danger');
    btnSaveNewPassword[!hsd['applyNewKey'] ? 'addClass' : 'removeClass']('d-none');
    btnClearNewPassword[!hsd['applyNewKey'] ? 'addClass' : 'removeClass']('d-none');
  }
  let inpKeyDest = $('#inpKeyDestination');
  inpKeyDest.focus(function () {
    if (selectedHSD)
      btnClearKeyDestination.removeClass('d-none');
  });
  function hideClearDestButton() {
    setTimeout(function () {
      if (tripleClick !== 3)
        return;
      btnClearKeyDestination.addClass('bg-danger');
      setTimeout(function () {
        btnClearKeyDestination.addClass('d-none');
        btnClearKeyDestination.removeClass('bg-danger');
      },250);
    },250);
  }
  inpKeyDest.blur(hideClearDestButton);

  let tripleClickTimer = 0;
  let tripleClick = 3;
  let lbl3ClickDeleteDestination = $('#lbl3ClickDeleteDestination');
  btnClearKeyDestination.click(function () {
    event.preventDefault();
    lbl3ClickDeleteDestination.html((3-(--tripleClick)).toString()+'/3');
    if (tripleClick > 0) {
      lbl3ClickDeleteDestination.removeClass('d-none');
      if (tripleClickTimer) clearTimeout(tripleClickTimer);
      tripleClickTimer = setTimeout(function () {
        lbl3ClickDeleteDestination.addClass('d-none');
        tripleClick = 3;
        hideClearDestButton();
      }, 2000);
      return false;
    }
    btnClearKeyDestination.addClass('d-none');
    let tgt = inpKeyDest.val().replaceAll('/','');
    for (let hst in objHSD)
      for (let svc in objHSD[hst])
        for (let dst in objHSD[hst][svc])
          if (tgt === hst+svc+dst) {
            delete objHSD[hst][svc][dst];
            if ($.isEmptyObject(objHSD[hst][svc])) {
              delete objHSD[hst][svc];
              if ($.isEmptyObject(objHSD[hst])) {
                delete objHSD[hst];
              }
            }
            selectedHSD = undefined;
            localStorage[lsHSD] = JSON.stringify(objHSD);
            selHSD.find('#'+hst+'_'+svc+'_'+dst).remove();
            resetAllControls(1);
            break;
          }
  });
  function passwordsFromSource(e, pass) {
    if (event) event.preventDefault();
    if (isQrCodeScannedFlag) {
      if (isQrCodeScannedFlag === 2 && !pass) {
        let hsd = $(this).parent()[0].id.split('_');
        inpCurrentPassword.val(objHSD[hsd[0]][hsd[1]][hsd[2]]['currentKey']);
      }
      return;
    }
    let the = pass ? pass : $(this).html();
    inpKeyDest.val(the);
    let arr = the.split('/');
    let obj = {hostName: arr[0], serviceName: arr[1], destName: arr[2]};
    let dest = arr[0]+'/'+arr[1]+'/'+arr[2];
    localStorage[lsSelectedHSD] = arr[0]+'_'+arr[1]+'_'+arr[2];
    selectedHSD = objHSD[obj.hostName][obj.serviceName][obj.destName];
    fillPasswordInputs(selectedHSD);
    //lblQrShow.removeClass('d-none');
    //lblQrCreate.addClass('d-none');
    btnShowQrCode.find('svg').attr('fill', bgColorSuccess);
    btnAutoGenerateNewPassword[selectedHSD['newKeyIsAutoGenerated'] ? 'addClass' : 'removeClass' ]('text-success-highlight');
    btnGenerateNewPassword[selectedHSD['newKeyIsAutoGenerated'] ? 'addClass' : 'removeClass' ]('bg-success');
    setTimeout(function () {
      btnShowQrCode.find('svg').attr('fill', colorHighlightSuccess);
    },250);
  }
  selHSD.find('a').click(passwordsFromSource);
  if (localStorage[lsSelectedHSD])
    setTimeout(function () {
      let selectedHSD = selHSD.find('#'+localStorage[lsSelectedHSD]);
      if (selectedHSD.length) $(selectedHSD[0]).find('a').click();
      else localStorage.removeItem(lsSelectedHSD);
    }, 200);

  let openSaveFileArea = $('#openSaveFileArea');
  let inpFileDataPassword = $('#inpFileDataPassword');
  function showSaveFileArea() {
    event.preventDefault();
    let tgt = $($(this).attr('data-bs-target'));
    tgt[tgt.hasClass('d-none') ? 'removeClass' : 'addClass']('d-none');
  }
  $('#btnCloseOpenSaveFileArea').click(showSaveFileArea);
  $('#btnCloseAlertIncomatibleQRCodePanel').click(showSaveFileArea);
  selHSD.find('#actOpenSaveFile').click(showSaveFileArea);
  $('#btnSaveFile').click(async function () {
    let thePass = inpFileDataPassword.val();
    if (!thePass.length) thePass = '.';
    TOTP6.generateSecretKey(thePass, function (key) {
      let e= new age.Encrypter();
      e.setPassphrase(key);
      //e.addRecipient(publicKey);
      e.encrypt(localStorage[lsHSD]).then(
        async encryptedData => {
          let theData = thePass === '.' ? localStorage[lsHSD] : age.armor.encode(encryptedData);
          try {
            const handle = await window.showSaveFilePicker({
              suggestedName: 'qrauth-' + YYYYMMDDHHmmSS() + (thePass === '.' ? '.json' : '.age'),
            });
            const writable = await handle.createWritable();
            await writable.write(theData);
            await writable.close();
          } catch (err) {
            //saveViaAnchor(theData);
            console.log(err);
          }
        });
    })
  });
  $('#btnOpenFile').click(async function () {
    let thePass = inpFileDataPassword.val();
    if (!thePass.length) thePass = '.';
    TOTP6.generateSecretKey(thePass, async function (key) {
      const [fileHandle] = await window.showOpenFilePicker({
        types: [{
          accept: {'text/plain': [(thePass === '.' ? '.json' : '.age')]}
        }]
      });

      const file = await fileHandle.getFile();
      const encryptedData = await file.text();
      if (thePass === '.') {
        try {
          const obj = JSON.parse(encryptedData);
          localStorage[lsHSD] = JSON.stringify(obj);
          console.log(obj);
        } catch (error) {
          console.error("Failed to parse JSON:", error);
        }
      } else {
        //let data = Uint8Array.fromBase64(encryptedData);
        let d= new age.Decrypter();
        d.addPassphrase(key);
        d.decrypt(age.armor.decode(encryptedData), 'text').then((data) => {
          try {
            const obj = JSON.parse(data);
            localStorage[lsHSD] = JSON.stringify(obj);
            location.reload();
          } catch (error) {
            console.error("Failed to parse JSON:", error);
          }
        })
      }
    })
  });

  function showInputPassword(pass) {
    if (event) event.preventDefault();
    let the = $(this);
    if (typeof pass === 'string') {
      inpCurrentPassword.val(pass);
      the = labelOTPcode;
    }
    let tgtInp = $(the.attr('data-bs-target'));
    let isHidden = (tgtInp.attr('type') === 'password');
    tgtInp.attr('type', isHidden ? 'text' : 'password');
    the[ isHidden ? 'addClass' : 'removeClass' ]('bg-danger');
  }
  btnShowCurrentPassword.click(showInputPassword);
  btnShowNewPassword.click(showInputPassword);
  $('#btnShowSaveFilePassword').click(showInputPassword);
  labelOTPcode.click(function () {
    event.preventDefault();
    TOTP6.generateSecretKey(selectedHSD.publicKey + inpCurrentPassword.val(), showInputPassword)
  });


  let refreshOtpIntervalTimer = 0;
  let refreshOtpTimeout = 0;
  function activateProgressBar(periodSeconds, intervalSeconds, callback) {
    progressBar.css('width', Math.floor(periodSeconds/intervalSeconds*100)+'%');
    //if (refreshOtpTimeout) clearTimeout(refreshOtpTimeout);
    if (callback === refreshOtp)
      refreshOtpTimeout = setTimeout(refreshOtp, periodSeconds * 1000);
    if (refreshOtpIntervalTimer)
      clearInterval(refreshOtpIntervalTimer);
    refreshOtpIntervalTimer = setInterval(function () {
      if (periodSeconds-- <= 1) {
        clearInterval(refreshOtpIntervalTimer);
        progressBar.css('width', '0%');
        if (callback) callback();
      } else
      progressBar.css('width', (periodSeconds > 0 ? Math.floor(periodSeconds/intervalSeconds*100) : 100) +'%');
    },1000);
  }

  let currentOTPsecret = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  let qrCodeArea = document.getElementById("qrCodeImgArea");
  async function refreshOtp(e, OTPsecret) {
    currentOTPsecret = OTPsecret ? OTPsecret : currentOTPsecret;
    let qrc = await TOTP6.genCode(currentOTPsecret);
    $(qrCodeArea).html('');
    let w = cardArea.width();
    new QRCode(qrCodeArea, {
      text: qrc,
      width: w-40,
      height: w-40,
      colorDark : "#000000",
      colorLight : "#ffffff",
      correctLevel : QRCode.CorrectLevel.H
    });
    labelOTPcode.html(qrc.slice(0, qrc.length>>1)+'-'+qrc.slice(qrc.length>>1));

    if (!$(qrCodeArea).hasClass('d-none')) {
      if (selectedHSD.usbIP !== '0.0.0.0') {
        let requrl = 'http://'+selectedHSD.usbIP+':'+selectedHSD.usbPort;
        fetch(requrl + '/&'+qrc,{mode: 'no-cors'}).then(response => {
          if (response.type === 'opaque')
            stopShowQRcode();
        });
      } else
      if (switcherPTPMode[0].checked && fileHandleQRAuth) {
        try {
          const writable = await fileHandleQRAuth.createWritable();
          await writable.write(qrc);
          await writable.close();
        } catch (err) {
          console.log(err);
        }
      }
      progressBar.removeClass('bg-warning');
      progressBar.addClass('bg-success');
      activateProgressBar(30 - Math.floor((Date.now() / 1000) % 30), 30, refreshOtp);
    } else
      stopShowQRcode();
  }
  function resetAllControls(force) {
    //lblScanQrCode.removeClass('text-black');
    //lblQrCreate.addClass('text-black');
    btnKeyDestList.addClass('btn-outline-success btn-outline-secondary');
    if (force) {
      inpKeyDest.val('');
      inpCurrentPassword.val('');
      inpNewPassword.val('');
      //lblQrShow.addClass('d-none');
      //lblQrCreate.addClass('d-none');
      btnRevertPreviousPassword.addClass('d-none');
      btnSaveNewPassword.addClass('d-none');
      btnClearNewPassword.addClass('d-none');
      btnKeyDestList.removeClass('btn-outline-success');
      btnAutoGenerateNewPassword.removeClass('text-success-highlight');
      btnGenerateNewPassword.removeClass('bg-success-highlight');
    }
    btnShowQrCode.find('svg').attr('fill', 'black');
    btnScanSessionPubkey.find('svg').attr('fill', 'white');
    labelOTPcode.addClass('d-none');
    $(qrCodeArea).html('');
    $(qrCodeArea).addClass('d-none');
    $(elQrCodeVideo).addClass('d-none');
    progressBar.css('width', '0%');
  }
  function stopShowQRcode(stReset) {
    clearInterval(refreshOtpIntervalTimer);
    clearTimeout(refreshOtpTimeout);
    resetAllControls();
    passwordsFromSource(0, inpKeyDest.val());
    preventDoubleClick = false;
    isQrCodeScannedFlag = 0;
  }
  let preventDoubleClick = false;
  function btnShowAction() {
    if (event) event.preventDefault();
    if (preventDoubleClick)
      return;
    preventDoubleClick = true;
    $(qrCodeArea).removeClass('bg-black');
    settingsArea.addClass('d-none');
    btnSettings.removeClass('bg-primary');
    whatTheArea.addClass('d-none');
    btnShowHelp.removeClass('bg-primary');
    if (!inpKeyDest.val() && isQrCodeScannedFlag !== 2) {
      inpKeyDest.addClass('bg-danger');
      setTimeout(function () {
        inpKeyDest.removeClass('bg-danger');
      }, 150);
      return;
    }
    if (inpCurrentPassword.val().length < 3) {
      inpCurrentPassword.addClass('bg-danger');
      setTimeout(function () {
        inpCurrentPassword.removeClass('bg-danger');
      }, 150);
      return;
    }
    if (isQrCodeScannedFlag === 1)
      return;
    if (isQrCodeScannedFlag === 2) {
      btnShowQrCode.find('svg').attr('fill', 'gray');
      btnScanSessionPubkey.find('svg').attr('fill', 'gray');
      //lblQrCreate.addClass('text-black');
      //lblScanQrCode.addClass('text-black');
      showAnimatedQRcode();
      return;
    }
    let isHidden = $(qrCodeArea).hasClass('d-none');
    $(qrCodeArea)[ isHidden ? 'removeClass' : 'addClass' ]('d-none');
    if (isHidden) {
      let pass = inpCurrentPassword.val();
      btnShowQrCode.find('svg').attr('fill', 'gray');
      labelOTPcode.removeClass('d-none');
      TOTP6.generateSecretKey(selectedHSD.publicKey + pass, refreshOtp);
    } else
      stopShowQRcode();
  }
  //lblQrShow.click(btnShowAction);
  //lblQrCreate.click(btnShowAction);
  btnShowQrCode.click(btnShowAction);

  btnRevertPreviousPassword.click(function () {
    event.preventDefault();
    let doShowPrevPass = (inpCurrentPassword.val() !== selectedHSD.previousKey);
    inpCurrentPassword.val(selectedHSD[doShowPrevPass ? 'previousKey' : 'currentKey']);
    inpCurrentPassword[doShowPrevPass ? 'addClass' : 'removeClass']('text-danger');
    btnClearPassword[doShowPrevPass ? 'removeClass' : 'addClass']('d-none');
    btnRevertPreviousPassword.find('span').html(doShowPrevPass ? '&#8635;' : '&#8634;'); // 11118/8635 | 11119/8634
  });
  btnClearPassword.click(function () {
    event.preventDefault();
    inpCurrentPassword.val(selectedHSD.currentKey);
    inpCurrentPassword.removeClass('text-danger');
    btnClearPassword.addClass('d-none');
    btnRevertPreviousPassword.addClass('d-none');
    delete selectedHSD.previousKey;
    localStorage[lsHSD] = JSON.stringify(objHSD);
  });

  inpCurrentPassword.change(function () {
    if (inpCurrentPassword.val().length > 5) {
    }
  });

  let elQrCodeVideo = document.getElementById('qrCodeScannerVideo');
  let scanner = null;
  let unlockButtonSaveNewPassword = false;
  let isQrCodeScannedFlag = 0;
  function showQRcodeAlert(addmsg) {
    let alertIncomatibleQRCodePanel = $('#alertIncomatibleQRCodePanel');
    alertIncomatibleQRCodePanel.removeClass('d-none');
    $('#additionalAlertMsg').html(addmsg || '');
    setTimeout(function () {
      alertIncomatibleQRCodePanel.addClass('d-none');
    }, 10000);
  }
  async function qrScanned(resp) {
    scanner.stop();
    isQrCodeScannedFlag = 0;
    clearInterval(refreshOtpIntervalTimer);
    progressBar.css('width', '0%');
    $(elQrCodeVideo).addClass('d-none');
    TOTP6.generateSecretKey(resp.data, async function (key) {
      let qrc = await TOTP6.genCode(key, Date.now() / 1000);
      $(qrCodeArea).removeClass('d-none');
      $(qrCodeArea).addClass('bg-black');
      $(qrCodeArea).html('QRC controle code: &nbsp; <span style="font-size: x-large; color: yellow;">'+
          qrc.slice(0, 3) + '-' + qrc.slice(3)+'</span><br><code style="color: gray">['+resp.data +']</code>');
    });
    let arr = resp.data.split('/');
    if (arr.length < 5) { showQRcodeAlert(resp.data); return }
    let ipport = arr[4].split(':');
    let obj = {
      qrcCodeFragment: arr[0],
      hostName: arr[1],
      serviceName: arr[2],
      destName: arr[3],
      usbIP: ipport[0],
      usbPort: ipport[1],
      pubkey: arr[5]
    };
    if (obj.qrcCodeFragment !== '111' ||
        obj.pubkey.indexOf('age1') !== 0 ||
        !(/^((\d){1,3}\.){3}(\d){1,3}$/.test(obj.usbIP)) ||
        (obj.usbPort !== '80' && obj.usbPort !== '8080') ||
        obj.hostName.length > 64 || obj.serviceName.length > 64 || obj.destName.length > 64) {
      showQRcodeAlert();
      return
    }
    let path = obj.hostName + '/' + obj.serviceName + '/' + obj.destName;
    inpKeyDest.val(path);
    if (!objHSD[obj.hostName])
      objHSD[obj.hostName] = {};
    if (!objHSD[obj.hostName][obj.serviceName])
      objHSD[obj.hostName][obj.serviceName] = {};
    if (!objHSD[obj.hostName][obj.serviceName][obj.destName])
      objHSD[obj.hostName][obj.serviceName][obj.destName] = {};
    selectedHSD = objHSD[obj.hostName][obj.serviceName][obj.destName];
    selectedHSD['path'] = path;
    selectedHSD['usbIP'] = obj.usbIP;
    selectedHSD['usbPort'] = obj.usbPort;
    selectedHSD['publicKey'] = obj.pubkey;
    if (selectedHSD['newKeyIsAutoGenerated'])
      autoGenerateNewPasswordInTheInput();
    fillPasswordInputs(selectedHSD);
    btnShowQrCode.find('svg').attr('fill', 'yellow');
    //lblQrCreate.removeClass('text-black');
    btnScanSessionPubkey.find('svg').attr('fill', 'yellow');
    //$('#areaNewPassword').removeClass('d-none');
    isQrCodeScannedFlag = 2;
  }
  function initScanner() {
    scanner = new QrScanner(elQrCodeVideo, qrScanned, {
        highlightScanRegion: true,
        highlightCodeOutline: true
      }
    );
  }
  let unlockedIcon = $('#unlockedIcon');
  let qrAnimationTimeout = 0;
  let fileHandleQRAuth = null;
  function showAnimatedQRcode() {
    let w = $('#mainContainer').width();
    let arr = inpKeyDest.val().split('/');
    let hsd = selectedHSD;
    let isNewDest = (!hsd['currentKey'] || inpKeyDest.val() !== selectedHSD.path);

    let e= new age.Encrypter();
    e.addRecipient(hsd.publicKey);
    let sendData = inpCurrentPassword.val();
    if (inpNewPassword.val() !== '')
      sendData += '\n' + inpNewPassword.val();
    e.encrypt(sendData).then(
      async encryptedData => {
        $(qrCodeArea).removeClass('d-none');
        let curKey = inpCurrentPassword.val();
        if (curKey && curKey !== hsd['currentKey'])
          hsd['previousKey'] = hsd['currentKey'];
        hsd['currentKey'] = curKey;
        if (inpNewPassword.val() !== '') {
          btnSaveNewPassword.addClass('bg-danger');
          btnSaveNewPassword.removeClass('d-none');
          btnClearNewPassword.removeClass('d-none');
          unlockButtonSaveNewPassword = true;
          hsd['applyNewKey'] = inpNewPassword.val();
        }
        localStorage[lsHSD] = JSON.stringify(objHSD);
        localStorage[lsSelectedHSD] = arr[0]+'_'+arr[1]+'_'+arr[2];
        let dest = selectedHSD.path;
        if (isNewDest)
          selHSD.prepend(hsdHtmlTemplate.replace('#id', dest.replaceAll('/','_')).replace('#html',dest));
        const data = encryptedData.toBase64();
        if (switcherPTPMode[0].checked) {
          $(qrCodeArea).addClass('d-none');
          try {
            //const handle = await window.showSaveFilePicker({suggestedName: 'qrauth.txt', types: [{accept: {'text/plain': '.txt'}}]});
            const writable = await fileHandleQRAuth.createWritable();
            await writable.write(data);
            await writable.close();
            let pollingTimerHandle = setTimeout(async function () {
              if (!refreshOtpIntervalTimer)
                clearTimeout(pollingTimerHandle);
              try {
                const file= await fileHandleQRAuth.getFile();
              } catch (e) {
                if (e.name === 'NotFoundError') {
                  clearInterval(refreshOtpIntervalTimer);
                  unlockedIcon.removeClass('d-none');
                  setTimeout(function () {unlockedIcon.addClass('d-none');}, 3000);
                  clearTimeout(pollingTimerHandle);
                } else
                  console.log(e);
              }
            },1000);
          } catch (err) {
            console.log(err);
          }
          isQrCodeScannedFlag = 0;
          passwordsFromSource(0, inpKeyDest.val());
          preventDoubleClick = false;
          return;
        }
        if (selectedHSD.usbIP !== '0.0.0.0') {
          let requrl = 'http://'+selectedHSD.usbIP+':'+selectedHSD.usbPort;
          //console.log(requrl);
          setTimeout(function () {
            if (qrAnimationTimeout > 2)
              navigator.sendBeacon(requrl, 'GET /&'+data + ' end\r\n');
            /*else
            if (selectedHSD.serviceName.replace(/luks|crypttab|initramfs/i, '!') === '!') {
              passwordsFromSource(0, inpKeyDest.val());
              $(qrCodeArea).addClass('bg-black');
              $(qrCodeArea).removeClass('d-none');
              $(qrCodeArea).html('<code style="color: gray">Click button below if destination still in countdown state<br>' +
                  '<button class="btn btn-secondary mt-2 mb-0 pt-0 pb-0" onclick="location.reload();" style="font-size: 2em">&#10227;</button>');
              setTimeout(function () {
                $(qrCodeArea).html('');
                $(qrCodeArea).addClass('d-none');
                $(qrCodeArea).removeClass('bg-black')
              }, 10000);
            }*/
          }, 2000);
          fetch(requrl + '/&'+data,{mode: 'no-cors'}).then(response => {
            if (response.type === 'opaque') {
              qrAnimationTimeout = 1;
              unlockedIcon.removeClass('d-none');
              setTimeout(function () {unlockedIcon.addClass('d-none');}, 3000);
            }
          });
        }
        let datalen = data.length;
        let numOfChunks = parseInt(localStorage['QrChunksNumber'], 10);
        let numOfChunksDigits = (numOfChunks > 9) ? 2 : 1;
        let chunklen = Math.floor(datalen / numOfChunks);
        if (numOfChunks - datalen % chunklen < numOfChunks) {
          chunklen++;
          numOfChunks = Math.floor(datalen / chunklen);
          if (datalen % chunklen) numOfChunks++;
          numOfChunksDigits = (numOfChunks > 9) ? 2 : 1;
        }
        let fulllen = 0;
        let i = 0;
        $(qrCodeArea).html('');
        while (++i <= numOfChunks && chunklen) {
          let chunkStr =
            numOfChunksDigits.toString()
            + numOfChunks.toString()
            + ('00' + i).slice(-numOfChunksDigits)
            + data.substring(fulllen, fulllen+chunklen);
          new QRCode(qrCodeArea, {
            text: chunkStr,
            width: w-40,
            height: w-40,
            colorDark: "#000000",
            colorLight: "#ffffff",
            correctLevel: QRCode.CorrectLevel.H
          });
          fulllen += chunklen;
          if (datalen - fulllen < chunklen)
            chunklen = datalen - fulllen;
        }
        let qrImgPool = $(qrCodeArea).find('canvas,img');
        qrImgPool.addClass('d-none');
        $(qrImgPool[0]).removeClass('d-none');
        $(qrImgPool[1]).removeClass('d-none');
        let activeQrImgIdx = 0;
        qrAnimationTimeout = 180;
        progressBar.css('width', '1000%');
        let qrInterval = setInterval(function () {
          if (inpNewPassword.val() !== '' && qrAnimationTimeout % 4 === 0)
            btnSaveNewPassword[btnSaveNewPassword.hasClass('bg-danger') ? 'removeClass' : 'addClass'] ('bg-danger');
          $(qrImgPool[activeQrImgIdx++]).addClass('d-none');
          $(qrImgPool[activeQrImgIdx++]).addClass('d-none'); // it is not repeated of prev line!
          if (activeQrImgIdx > qrImgPool.length-1)
            activeQrImgIdx = 0;
          $(qrImgPool[activeQrImgIdx]).removeClass('d-none');
          $(qrImgPool[activeQrImgIdx+1]).removeClass('d-none');
          if (--qrAnimationTimeout <= 0) {
            resetAllControls();
            btnShowQrCode.find('svg').attr('fill', $('.bg-success').css('backgroundColor'));
            clearInterval(qrInterval);
            isQrCodeScannedFlag = 0;
            passwordsFromSource(0, inpKeyDest.val());
            preventDoubleClick = false;
          } else
          progressBar.css('width', Math.floor(qrAnimationTimeout/180*100) +'%');
        },parseInt(localStorage['QrChunkInterval']));
      });
  }
  $(qrCodeArea).click(function () {
    event.preventDefault();
    if (qrAnimationTimeout)
      qrAnimationTimeout = 1;
    else
      stopShowQRcode();
  });
  async function scanQRcode() {
    if (event) event.preventDefault();
    isQrCodeScannedFlag = 1;
    stopShowQRcode();
    $(qrCodeArea).addClass('d-none');
    $(elQrCodeVideo).removeClass('d-none');
    //lblQrCreate.removeClass('d-none');
    //lblQrShow.addClass('d-none');
    if (!scanner)
      initScanner();
    settingsArea.addClass('d-none');
    btnSettings.removeClass('bg-primary');
    whatTheArea.addClass('d-none');
    btnShowHelp.removeClass('bg-primary');
    if (switcherPTPMode[0].checked) {
      try {
        [fileHandleQRAuth] = await window.showOpenFilePicker({suggestedName: 'qrauth.txt', types: [{accept: {'image/png': '.png', 'text/plain': '.txt'}}]});
        if (fileHandleQRAuth) {
          const file = await fileHandleQRAuth.getFile();
          const data = await file.text();
          qrScanned({data: data});
        }
      } catch (e) {
      }
    } else
      scanner.start().then(() => {});
    progressBar.removeClass('bg-success');
    progressBar.addClass('bg-warning');
    activateProgressBar(15, 15, function () { // stop scanner cam in 15s of inactivity
      scanner.stop();
      $(elQrCodeVideo).addClass('d-none');
      stopShowQRcode();
    });
    /*if (inpCurrentPassword.val() !== '') {
    } else {
      inpCurrentPassword.addClass('bg-danger');
      setTimeout(function () {
        inpCurrentPassword.removeClass('bg-danger');
      }, 150);
    }*/
  }

  let controlKeys = {
    'QrChunksNumber': 'to define QR chunks number for data package',
    'QrChunkInterval': 'QR chunk display time in ms',
    'PasswordsStorageSize': 'used to define size of history passwords storage base records per destination',
  };
  for (let controlName in controlKeys) {
    let controlInput = $('#inp' + controlName);
    let controlInputMin = parseInt(controlInput.attr('min'));
    let controlInputMax = parseInt(controlInput.attr('max'));
    let controlInputStep = parseInt(controlInput.attr('step'));
    let controlButton = $('button[data-bs-target=' + controlName + ']');
    let controlLabel = $('#lbl' + controlName);
    if (!localStorage[controlName])
      localStorage[controlName] = controlInput.val();
    controlLabel.html(localStorage[controlName]);
    controlInput.val(localStorage[controlName]);
    controlInput.on('input', function () {
      localStorage[controlName] = $(this).val();
      controlLabel.html(localStorage[controlName]);
    });
    controlButton.on('click', function () {
      if (event) event.preventDefault();
      let addsub = ($(this).text() === '+' ? +1 : -1) * controlInputStep;
      let newval = parseInt(localStorage[controlName]) + addsub;
      if (newval >= controlInputMin && newval <= controlInputMax) {
        controlInput.val(newval);
        localStorage[controlName] = newval;
        controlLabel.html(localStorage[controlName]);
      }
    });
  }
  $('#qrChunksQuantity').html(localStorage['QrChunksNumber']);

  let switcherKeys = {
    'TSInNewPassword' : {checked: false, val: "YYMMDDhhmmss:"},
    'CCInNewPassword' : {checked: false, val: "Some passphrase..."}
  }
  for (let controlName in switcherKeys) {
    if (localStorage[controlName])
      switcherKeys[controlName] = JSON.parse(localStorage[controlName])
    let controlSwitcher = $('#sw' + controlName);
    controlSwitcher[0].checked = switcherKeys[controlName].checked;
    controlSwitcher.on('change', function () {
      if (event) event.preventDefault();
      let the = $(this);
      let tgt = the.attr('data-bs-target');
      if (tgt && $(tgt).val() === '') {
        $(tgt).addClass('bg-danger');
        setTimeout(function () {
          $(tgt).removeClass('bg-danger');
          $(tgt).focus();
          the[0].checked = false;
        }, 500);
      } else
        localStorage[controlName] = JSON.stringify({checked: this.checked, val: $(tgt).val()});
    });
    let controlSwitherInput = $(controlSwitcher.attr('data-bs-target'));
    controlSwitherInput.val(switcherKeys[controlName].val);
    controlSwitherInput.on('keyup', function () {
      let controlName = $(this).attr('data-bs-target');
      let ccInput = $('#inp' + controlName);
      if (switcherKeys[controlName].val !== ccInput.val()) {
        let tgt = $('#sw' + controlName);
        if (tgt[0].checked) tgt[0].checked = false;
        tgt.addClass('bg-warning');
        setTimeout(function () {
          tgt.removeClass('bg-warning');
        }, 250);
      }
    });
    controlSwitherInput.on('focus', function () {
      if ($(this).attr('type') === 'password')
        $(this).attr('type', 'text');
    });
    controlSwitherInput.on('blur', function () {
      let the = $(this);
      if (the[0].id === 'inpCCInNewPassword')
        the.attr('type', 'password');
    });
    controlSwitherInput.on('change', function () {
      let the = $(this);
      let tgt = $('#sw'+the.attr('data-bs-target'));
      tgt[0].checked = false;
      setTimeout(function() {
        console.log(the[0].id)
        if (the[0].id === 'inpCCInNewPassword')
          the.attr('type', 'password');
        tgt.click()
        tgt.focus();
      }, 250);
    });
  }


  btnScanSessionPubkey.click(scanQRcode);
  //lblScanQrCode.click(scanQRcode);
  $('#btnScanSessionPubkey4pwd').click(scanQRcode);

  function showHideArea() {
    if (event) event.preventDefault();
    let the = $(this);
    let tgtEl = $(the.attr('data-bs-target'));
    var isHidden = !tgtEl.hasClass('d-none');
    the[ isHidden ? 'removeClass' : 'addClass' ]('bg-primary');
    tgtEl[ isHidden ? 'addClass' : 'removeClass' ]('d-none');
    //cardArea[ !isHidden ? 'addClass' : 'removeClass' ]('d-none');
  }
  btnSettings.click(showHideArea);
  btnShowHelp.click(showHideArea);

  function autoGenerateNewPasswordInTheInput() {
    let newKey = TOTP6.generatePassword(8);
    if (localStorage['TSInNewPassword']) {
      let obj = JSON.parse(localStorage['TSInNewPassword']);
      if (obj.checked) { //TODO: need correct work with format string
        let tsfmt = obj.val;
        newKey = YYYYMMDDHHmmSS().substr(2) + newKey;
      }
    }
    if (localStorage['CCInNewPassword']) {
      let obj = JSON.parse(localStorage['CCInNewPassword']);
      if (obj.checked && obj.val)
        TOTP6.generateSecretKey(
          newKey + obj.val,
          async function (OTPkey) {
            let qrc = await TOTP6.genCode(OTPkey, Date.now() / 1000);
            $('#inpNewPassword').val(newKey + qrc);
          }
        );
    } else
      $('#inpNewPassword').val(newKey);
  }

  btnGenerateNewPassword.click(function () {
    event.preventDefault();
    let currPass = inpNewPassword.val();
    if (!currPass || currPass.length >= 64) currPass = '';
    currPass = TOTP6.generatePassword(8) + currPass;
    inpNewPassword.val(currPass);
    $('#lblNewPasswordsLength').html('(' + currPass.length + ' chars)');
  });
  let lbl3ClickDeleteNewPassword = $('#lbl3ClickDeleteNewPassword');
  btnClearNewPassword.click(function () {
    event.preventDefault();
    lbl3ClickDeleteNewPassword.html((3-(--tripleClick)).toString()+'/3');
    if (tripleClick > 0) {
      lbl3ClickDeleteNewPassword.removeClass('d-none');
      if (tripleClickTimer) clearTimeout(tripleClickTimer);
      tripleClickTimer = setTimeout(function () {
        lbl3ClickDeleteNewPassword.addClass('d-none');
        tripleClick = 3;
      }, 2000);
      return false;
    }
    $('#inpNewPassword').val('');
    delete selectedHSD.applyNewKey;
    localStorage[lsHSD] = JSON.stringify(objHSD);
    btnSaveNewPassword.removeClass('bg-danger');
    btnSaveNewPassword.addClass('d-none');
    btnClearNewPassword.addClass('d-none');
    $('#lblNewPasswordsLength').html('');
    unlockButtonSaveNewPassword = false;
    lbl3ClickDeleteDestination.addClass('d-none');
    tripleClick = 3;
  });
  btnSaveNewPassword.click(async function () {
    event.preventDefault();
    if (unlockButtonSaveNewPassword || selectedHSD['applyNewKey']) {
      if (selectedHSD['applyNewKey']) delete selectedHSD.applyNewKey;
      selectedHSD.currentKey = inpNewPassword.val();
      inpCurrentPassword.val(selectedHSD.currentKey);
      localStorage[lsHSD] = JSON.stringify(objHSD);
      inpNewPassword.val('');
      btnSaveNewPassword.removeClass('bg-danger');
      btnSaveNewPassword.addClass('d-none');
      btnClearNewPassword.addClass('d-none');
      unlockButtonSaveNewPassword = false;
      let lsKeysHistory = lsKeysHistoryPrefix + inpKeyDest.val();
      let arr = localStorage[lsKeysHistory] ? JSON.parse(localStorage[lsKeysHistory]) : [];
      arr.unshift(YYYYMMDDHHmmSS() + ': ' + selectedHSD.currentKey);
      if (arr.length > localStorage['PasswordsStorageSize'])
        arr.pop();
      localStorage[lsKeysHistory] = JSON.stringify(arr);
    }
  });
  $('#btnCopyFromClipboard').click(async function () {
    event.preventDefault();
    try {
      inpCurrentPassword.val(await navigator.clipboard.readText());
    } catch (err) {console.error(err);}
  });
  $('#btnCopyToClipboard').click(async function () {
    event.preventDefault();
    try {
      await navigator.clipboard.writeText(inpCurrentPassword.val());
    } catch (err) {console.error(err);}
  });


  $('#btnPubkeyByUSB').click(async function () {
    /* TODO: may be next time...
    navigator.bluetooth.requestDevice({acceptAllDevices: true})
        .then(device => {
          device.gatt.connect().then(server => {
            server.getPrimaryService(0x1133).then(service => {
              service.getCharacteristic(0x2A4D).then(characteristic => {
                characteristic.startNotifications().addEventListener('characteristicvaluechanged',
                    function (e) {
                      console.log(e);
                    });
              })
            })
          })
          //device.addEventListener('gattserverdisconnected', onDisconnected);
        });*/
  });
  let labelVersion = $('#labelVersion');
  let btnUpdateVersion = $('#btnUpdateVersion');
  caches.keys().then(async function (cacheNames) {
    labelVersion.val(cacheNames[0]);
    if (navigator.onLine) {
      try {
        const response = await fetch('./sw.js?'+Date.now(), {priority: 'low', cache: 'no-store'});
        if (response.ok) {
          response.text().then(data => {
            let vers = data.replace(/\n/g,'').replace(/^.*CACHE_NAME = '/,'').replace(/'.*/g,'');
            if (vers !== cacheNames[0]) {
              labelVersion.addClass('text-warning');
              btnUpdateVersion.addClass('text-warning fw-bold');
              btnUpdateVersion.click(function () {
                caches.delete(cacheNames);
                location.reload(true);
              });
            }
          });
        }
      } catch (err) {
        console.log(err);
      }
    }
  });

}

$(document).ready(prepareControls);
