#!/bin/bash
# usage examples:
# qrauth | sudo -S -v && sudo -i
# qrauth | passwd


#set +e
#TTY=/dev/stdout
TTY=/dev/stderr
#TTY=/dev/null

SELFPID=$$
SESSPUBKEY="SESSPUBKEY"

KEYRING_ID=`keyctl search @u user "$SESSPUBKEY" 2>/dev/null`
if [ ! -z "$KEYRING_ID" ]; then
  keyctl unlink $KEYRING_ID >$TTY
fi

KEYRING_ID=`age-keygen 2>/dev/null | grep AGE-SECRET-KEY | keyctl padd user "$SESSPUBKEY" @u`
PUBKEY=`keyctl pipe $KEYRING_ID | age-keygen -y`

USBIFCIP="0.0.0.0"
for interface in /sys/class/net/*; do
  ifc=$(readlink "$interface")
  if [[ "$ifc" == */usb* ]] >$TTY; then
    ifcn=${interface#/sys/class/net/}
    USBIFCIP=$(ifconfig $ifcn | grep netmask | awk '{print $2}' | tr -d '\n')
    echo "USBIFCIP: $USBIFCIP">$TTY
  fi
done

HOSTNAME=$(hostname)
WHOAMI=$(whoami)
if [ -z "$HOSTNAME" ]; then
  HOSTNAME="HOSTNAME"
fi
PUBKEY=111/$HOSTNAME/qrauth/$WHOAMI/$USBIFCIP/$PUBKEY

echo " ">$TTY
qrencode -t ANSI256UTF8 "$PUBKEY">$TTY
echo "Please scan public key qrcode...">$TTY
echo "and now 62 seconds of countdown to stop(or press Ctrl+C)...">$TTY

tmpfifo=/tmp/qrauth.nc.fifo
mkfifo $tmpfifo
(
cat $tmpfifo | nc -l -p 54321 | grep --line-buffered GET | \
while read -sr get >/dev/null; do
  get=${get##*&}
  QRDATA=${get% *}
  echo -e "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-Length: 2\r\nAccess-Control-Allow-Origin: *\r\n\r\nOK" >$tmpfifo

  tmpfn=$(mktemp)
  echo "$QRDATA" | base64 -d >$tmpfn
  keyctl pipe $KEYRING_ID | age -d -i - $tmpfn | keyctl pupdate $KEYRING_ID  # workaround: because breaks from this WHILE does kill all VARS

  ZBARPID=$(ps -Af | grep zbarcam | grep $SELFPID | grep -v grep | awk '{print $2}')
  if [ ! -z "$ZBARPID" ]>/dev/null; then
    kill -2 $ZBARPID >/dev/null
  fi
  rm $tmpfn >/dev/null
  break
done
rm -f $tmpfifo >/dev/null
)>/dev/null &
FIFOPID=$!

BASE62="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
LEN=0
CNTR=""
TIMEOUT=62
(while [ -e $tmpfifo -a $TIMEOUT -gt 0 ]>/dev/null; do
  sleep 1 >/dev/null
  echo "$BASE62" | cut -zc$TIMEOUT >$TTY
  TIMEOUT=$((TIMEOUT-1))
 done
 kill -2 $(ps -Af | egrep "nc -l -p 54321" | grep -v grep | awk '{print $2}') >/dev/null
 kill -2 $(ps -Af | grep zbarcam | grep $SELFPID | grep -v grep | awk '{print $2}') >/dev/null
 keyctl unlink $KEYRING_ID>/dev/null
 KEYRING_ID=
# rm $tmpfifo >/dev/null
)&
TIMEOUTPID=$!
#echo "TIMEOUTPID: $TIMEOUTPID"

terminate() {
#  echo "." >$tmpfifo
#  kill -2 $(ps -Af | grep zbarcam | grep $SELFPID | grep -v grep | awk '{print $2}') 2>&1 >/dev/null
#  kill -9 $TIMEOUTPID 2>&1 >/dev/null
#  kill -2 $(ps -Af | grep "nc -l -p 54321" | awk '{print $2}') 2>&1 >/dev/null
#  keyctl unlink $KEYRING_ID>/dev/null
  echo ""
  exit 0
}
trap terminate INT TERM


zbarcam -q --nodisplay --nodbus --raw -Sdisable -Sqrcode.enable | \
while read -r QRCHUNK >/dev/null; do
  NDGTS=`echo $QRCHUNK | cut -c 1`
  NCHUNKS=`echo $QRCHUNK | cut -c 2-$((NDGTS+1))`
  ICHUNK=`echo $QRCHUNK | cut -c $((NDGTS+2))-$((NDGTS*2+1))`
  echo " ">$TTY
  echo -n "{$ICHUNK/$NCHUNKS: ">$TTY
  ICHUNK=$(echo "obase=10; ibase=10; ${ICHUNK}" | bc)
  QRCHUNK=`echo "$QRCHUNK" | cut -c $((NDGTS*2+2))-`
  f=$(echo "$BASE62" | cut -c$ICHUNK)
  if echo "$CNTR" | grep -q $f; then
    echo -n "$LEN} # ">$TTY
  else
    CNTR=$CNTR$f
    VARCHUNK="QRCHUNK$ICHUNK"
    eval "$VARCHUNK=\"$QRCHUNK\""
    LEN=$((LEN+1))
    echo -n "$LEN} ">$TTY
  fi
  if [ $LEN -eq $NCHUNKS ]>/dev/null; then
    QRDATA=""
    while [ $LEN -gt 0 ]; do
      VARCHUNK="QRCHUNK$LEN"
      eval "VAR=\$${VARCHUNK}"
      QRDATA=$VAR$QRDATA
      LEN=$((LEN-1))
    done

    tmpfn=$(mktemp)
    echo "$QRDATA" | base64 -d >$tmpfn
    keyctl pipe $KEYRING_ID | age -d -i - $tmpfn | keyctl pupdate $KEYRING_ID  # workaround: because breaks from this WHILE does kill all VARS
    rm $tmpfn
    kill -2 $(ps -Af | grep zbarcam | grep $SELFPID | grep -v grep | awk '{print $2}') >/dev/null
    echo "." >$tmpfifo
    rm -f $tmpfifo >/dev/null
    break
  fi
done

sleep 0.1
#if [ -e $tmpfifo ]>/dev/null; then
  echo "." >$tmpfifo
  rm -f $tmpfifo >/dev/null
#fi

echo "">$TTY
if [ ! -z $KEYRING_ID ]>/dev/null; then
  keyctl pipe $KEYRING_ID
  keyctl unlink $KEYRING_ID >/dev/null
fi
echo "">$TTY


NCPID=$(ps -Af | egrep "nc -l -p 54321" | grep -v grep | awk '{print $2}')
#echo "NCPID: $NCPID"
if [ ! -z "$NCPID" ] >/dev/null; then
  kill -2 $NCPID >/dev/null
#  kill -2 $FIFOPID 2>&1 >/dev/null
fi

sleep 0.1

TOPID=$(ps -A | grep $TIMEOUTPID)
if [ ! -z "$TOPID" ]; then
  kill -9 $TIMEOUTPID >/dev/null
fi

#echo "\nreturn the password(s) ...\n">$TTY

exit 0
