#!/bin/bash
# usage examples:
# qrauth | sudo -S -v && sudo -i
# qrauth | passwd


#set +e
#TTY=/dev/stdout
TTY=/dev/stderr
#TTY=/dev/null

SESSPUBKEY="SESSPUBKEY"

KEYRING_ID=`keyctl search @u user "$SESSPUBKEY" 2>/dev/null`
if [ ! -z "$KEYRING_ID" ]; then
  keyctl unlink $KEYRING_ID >$TTY
fi

KEYRING_ID=`age-keygen 2>/dev/null | grep AGE-SECRET-KEY | keyctl padd user "$SESSPUBKEY" @u`
PUBKEY=`keyctl pipe $KEYRING_ID | age-keygen -y`


HOSTNAME=$(hostname)
WHOAMI=$(whoami)
if [ -z "$HOSTNAME" ]; then
  HOSTNAME="HOSTNAME"
fi
PUBKEY=111/$HOSTNAME/qrauth/$WHOAMI/$PUBKEY

echo " ">$TTY
qrencode -t ANSI256UTF8 "$PUBKEY">$TTY
echo "Please scan public key qrcode and return enrypted password...">$TTY
echo "and now 62 seconds of countdown to stop(or press Ctrl+C)...">$TTY


BASE62="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
LEN=0
CNTR=""
TIMEOUT=62
SELFPID=$$
(while [ $TIMEOUT -gt 0 ]; do sleep 1; echo "$BASE62" | cut -zc$TIMEOUT >$TTY; TIMEOUT=$((TIMEOUT-1)); done;
keyctl unlink $KEYRING_ID>/dev/null;
kill -2 $(ps -Af | grep zbarcam | grep $SELFPID | awk '{print $2}') 2>&1  >/dev/null)&
TIMEOUTPID=$!

terminate() {
  kill -9 $TIMEOUTPID 2>&1 >/dev/null
  keyctl unlink $KEYRING_ID>/dev/null
  echo ""
  exit 0
}
trap terminate INT TERM


zbarcam -q --nodisplay --nodbus --raw -Sdisable -Sqrcode.enable | \
while read -r QRCHUNK >/dev/null; do
  NDGTS=`echo $QRCHUNK | cut -c 1`
  NCHUNKS=`echo $QRCHUNK | cut -c 2-$((NDGTS+1))`
  ICHUNK=`echo $QRCHUNK | cut -c $((NDGTS+2))-$((NDGTS*2+1))`
  echo " ">$TTY
  echo -n "{$ICHUNK/$NCHUNKS: ">$TTY
  ICHUNK=$(echo "obase=10; ibase=10; ${ICHUNK}" | bc)
  QRCHUNK=`echo "$QRCHUNK" | cut -c $((NDGTS*2+2))-`
  f=$(echo "$BASE62" | cut -c$ICHUNK)
  if echo "$CNTR" | grep -q $f; then
    echo -n "$LEN} # ">$TTY
  else
    CNTR=$CNTR$f
    VARCHUNK="QRCHUNK$ICHUNK"
    eval "$VARCHUNK=\"$QRCHUNK\""
    LEN=$((LEN+1))
    echo -n "$LEN} ">$TTY
  fi
  if [ $LEN -eq $NCHUNKS ]>/dev/null; then
    QRDATA=""
    while [ $LEN -gt 0 ]; do
      VARCHUNK="QRCHUNK$LEN"
      eval "VAR=\$${VARCHUNK}"
      QRDATA=$VAR$QRDATA
      LEN=$((LEN-1))
    done

    tmpfn=$(mktemp)
    echo "$QRDATA" | base64 -d >$tmpfn
    keyctl pipe $KEYRING_ID | age -d -i - $tmpfn | keyctl pupdate $KEYRING_ID  # workaround: because breaks from this WHILE does kill all VARS
    rm $tmpfn
    kill -2 $(ps -Af | grep zbarcam | grep $SELFPID | awk '{print $2}') 2>&1 >/dev/null
    break
  fi
done

kill -9 $TIMEOUTPID 2>&1 >/dev/null
#echo "\nreturn the password(s) ...\n">$TTY
keyctl pipe $KEYRING_ID
keyctl unlink $KEYRING_ID>/dev/null
exit 0
